services:
  cloudflared:
    image: 'cloudflare/cloudflared:latest'
    container_name: '${COMPOSE_PROJECT_NAME:-rtgh}-cloudflared'
    command: ["tunnel", "--no-autoupdate", "run", "--token", "${CLOUDFLARED_TOKEN}"]
    extra_hosts:
      - "host.docker.internal:host-gateway" # this is so we can access the host services
    restart: always
